const data = {
    products: [
        {id: 1,
        name: "heels",
        image: 'https://cdn.shopify.com/s/files/1/0037/3807/5202/products/DOLCEVITA-HEELS_BAYLOR_BLACKLEATHER-02_1024x1024.jpg?v=1642606458',
        description: "Go out in style with these sleek black heels! ",
        },
        {id: 2,
        name: "cardigan",
        image: 'https://cdn.shopify.com/s/files/1/1300/6871/products/Zebra-Cardigan-BlackNatural-2_1296x.jpg?v=1645002148',
        description: "Stay warm and fashionable with this multi-color cardigan! ",
         },
        {id: 3,
        name: "puffer",
        image: 'https://www.jacketars.com/wp-content/uploads/2021/01/Mens-Puffer-Red-Jacket.jpg',
        description: "Channel your inner New York with this thick red puffer jacket!",
        },
        {id: 4,
        name: "sneakers",
        image: 'https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw22670114/images/d_08/162050C_D_08X1.jpg?sw=406',
        description: "Classic high-top Converse sneakers. It goes with any outfit!",
        },
        {id: 5,
        name: "sunglasses",
        image: 'https://images.ray-ban.com/is/image/RayBan/805289602057_0000.png?impolicy=SEO_16x9',
        description: "You can never go wrong with these designer RayBan sunglasses.",
        },
        {id: 6,
        name: "slides",
        image: 'https://assets.burberry.com/is/image/Burberryltd/64eded1b5f02155675ab8f47dd3275835cabcc22?$BBY_V2_SL_1x1$&wid=2500&hei=2500',
        description: "Nice Burberry slides. Not too comfortable, but it lets the world know that you're boujee.",
        },
        {id: 7,
        name: 'blackshirt',
        image: 'https://media.cabiclio.com/products/404338-20220510042748.jpg?w=856',
        description: "A black shirt for women, but who says clothing has a gender?",
        },
        {id: 8,
        name: 'purse',
        image: 'https://cdn.shopify.com/s/files/1/2206/4495/products/Classic_Red_Front_no_zip_96d18fa9-cfae-4ad1-b140-77e285feb6a2_1200x1200.jpg?v=1639142777',
        description: "A nice red purse to go with your bold red lipstick. A true fashion statement!",
        },
        {id: 9,
        name: 'chain',
        image: 'https://www.zales.com/productimages/processed/V-20300755_0_400.jpg',
        description: "Made in Italy, this classic gold chain is made in 10k gold. Everyone loves a man with jewelry! ",
        },
        {id: 10,
        name: 'blackpants',
        image: 'https://cdna.lystit.com/200/250/tr/photos/leenewman/d1f087c5/bailey-44-Black-Lela-Vegan-Leather-Pants.jpeg',
        description: "Nice black leather pants. Goes with most outfits, depending on the occasion.",
        },
        {id: 11,
        name: 'sweatpants',
        image: 'https://www.rei.com/media/afc8d1c0-ce24-4ec9-bb63-cd6565a544b3?size=576x768',
        description: "Very comfortable olive green sweatpants.",
        },
        {id: 12,
        name: 'skirt',
        image: 'https://www.redvalentino.com/35/35468643fg_21_a.jpg',
        description: "An adorable plaid skirt for your classic schoolgirl outfit!",
        },
        {id: 13,
        name: 'blueshirt',
        image: 'https://img.abercrombie.com/is/image/anf/KIC_125-2703-3262-220_prod1?policy=product-medium&wid=350&hei=438',
        description: "A long-sleeve denim buttondown shirt that can be used for any occasion. Not too hot and not too cold! ",
        },
    ]
}
export default data;